name: Backport
on:
  pull_request_target:
    types: [closed, labeled]
    branches: [main, release-*]

# WARNING:
# When extending this action, be aware that $GITHUB_TOKEN allows write access to
# the GitHub repository. This means that it should not evaluate user input in a
# way that allows code injection.

jobs:
  backport:
    name: Backport Pull Request
    # Run the action if a PR is merged with backport labels
    # OR
    # when already merged PR is labeled with backport labels
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && startsWith(github.event.label.name, 'backport/')
        )
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # required to find all branches
          fetch-depth: 0
          token: ${{ secrets.GH_BACKPORT_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Create backport PRs
        uses: korthout/backport-action@v3.0.2
        with:
          # Inputs documented here: https://github.com/korthout/backport-action?tab=readme-ov-file#inputs
          github_token: ${{ secrets.GH_BACKPORT_TOKEN }}
          github_workspace: ${{ github.workspace }}

          # Regex pattern to match github labels
          # The capture group catches the target branch
          # i.e. label backport/release-1.23 will create backport PR for branch release-1.23
          label_pattern: ^backport\/([^ ]+)$

          pull_description: |-
            Automated backport to `${target_branch}`, triggered by a label in #${pull_number}.
            See ${issue_refs}.
