name: Lint docs

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - '**.md'
      - .github/workflows/docs.yml
      - .github/workflows/markdownlint-config.jsonc
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - '**.md'
      - .github/workflows/docs.yml
      - .github/workflows/markdownlint-config.jsonc
jobs:
  lint:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: articulate/actions-markdownlint@v1
        with:
          config: .github/workflows/markdownlint-config.jsonc
          ignore: autopilot
          version: 0.39.0
